### PR TITLE
Fixes #276: WebTestCase: Pass $omName to cleanDatabase()

### LINKED ISSUE #276: Clean Database doesn't work for EntityManagers other than default
Because of [this line](https://github.com/liip/LiipFunctionalTestBundle/blob/master/Test/WebTestCase.php#L487), the `cleanDatabase` call will always result in the default entity manager being cleaned. The `omName` Argument must be passed in the call to `loadFixtures()`.

### PR DESCRIPTION
**Pull request by alexislefebvre**
Fixes #276.

### CODE REVIEW

File: Test/WebTestCase.php [hunk 1]
```diff
@@ -545,7 +546,7 @@ public function loadFixtureFiles(array $paths = array(), $append = false, $omNam
         $om = $registry->getManager($omName);
 
         if ($append === false) {
-            $this->cleanDatabase($registry, $om);
+            $this->cleanDatabase($registry, $om, $omName);
```
Comment (alexislefebvre) [inline Test/WebTestCase.php]: I don't know how to retrieve the name `$omName` from `$om`, so I took the argument `$omName` directly.
